name: robs-workflow

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event name is:" ${{ github.event_name }}
          echo "branch name is:" ${{ github.head_ref || github.ref_name  }}
          
